-- Rollback for Stage 2 RLS
-- Disable RLS for the tables included in `20260318000000_stage2_enable_rls.sql`.

BEGIN;

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE organization_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE events DISABLE ROW LEVEL SECURITY;
ALTER TABLE slots DISABLE ROW LEVEL SECURITY;
ALTER TABLE signups DISABLE ROW LEVEL SECURITY;
ALTER TABLE nps_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE organizer_notification_digest DISABLE ROW LEVEL SECURITY;
ALTER TABLE templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE template_slots DISABLE ROW LEVEL SECURITY;

COMMIT;

